### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by bpajusco** [quantopian/zipline#1004]
Looks like I can't get zipline to work with Python 3.5. Is this a general conflict or is there something wrong in my setup of Python 3.5? I've used Anaconda and I got an exception when I tried to install zipline using conda. I then went ahead and tried pip install and got the following exception:

 File "/tmp/pip-3bizly_i-build/setup.py", line 73, in build_extensions
        numpy_incl = numpy.get_include()
    AttributeError: module 'numpy' has no attribute 'get_include'

```
----------------------------------------
```

Command "/home/bruno/anaconda/envs/py3k/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-3bizly_i-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-c7f7gwrj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-3bizly_i-build

Note that numpy works without trouble in all other instances where I'm calling the library,

**Comment by llllllllll** [comment]
We haven't begun testing zipline with python3.5 so some of the requirements might not work. Thanks for letting us know there is some more work to do to get 3.5 compat.

**Comment by FreddieV4** [comment]
x-ref https://github.com/quantopian/zipline/pull/1701

**Comment by mellertson** [comment]
I ran into the same issue tonight. It turned out to be a problem where I had multiple numpy packages installed. An older version was installed in `/usr/lib/python2.7` and the correct version was installed in `/usr/local/lib/python2.7`. 

Additionally, I had `PYTHONPATH=/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages`. PYTHONPATH was finding the older version of numpy before the correct version, so when inside the Python interpretter, it would import the older version of numpy. 

One thing which helped was opening a python session an executing the following code:

> import numpy as np
> print np.__version__
> print np.__path__

That should tell you exactly which version Python is using, and where it's installed. To fix the issue, I changed `PYTHONPATH=/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages`. And I also setup a virtual Python environment using the instructions [here](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/). I know I should have setup a virtual environment in the first place, but I was tired and being lazy.  Oh well, lesson learned!

I hope this help!

**Comment by FreddieV4** [comment]
We now support Python 3.5 in the latest release.

**Comment by lonelylinux** [comment]
> We now support Python 3.5 in the latest release.

Apparently not:

$ pip install zipline

yields this error:

ImportError: cannot import name 'main'

$ conda install -c Quantopian zipline

yields this error:

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - defaults/linux-64::numpy==1.14.0=py35h3dfced4_1
  - zipline -> bcolz[version='>=0.12.1,<1'] -> numpy=1.9
  - zipline -> numexpr[version='>=2.6.1']
Use "conda info <package>" to see the dependencies for each package.
-------------------------------------------------------------------------------------------------------------------

I'm seriously frustrated trying to find a tool that will just let me work with back-testing and stop wasting time with tools that don't work - or won't even install. 

Is there anyone here who has found a tool for back-testing that doesn't SUCK?

**Comment by freddiev4** [comment]
Hi @lonelylinux sorry it didn't install right away; installing Zipline is a little more involved than the average Python package. Have you read through the [Install Docs](http://www.zipline.io/install.html) to check that you have the necessary dependencies?
