### ISSUE TITLE
Zipline "latest" build has conflicting requirements

### ISSUE THREAD

**Issue by marketneutral** [quantopian/zipline#2322]
I am having trouble getting Zipline and Alphalens to work together in the same environment. I am filing this issue here, because I believe the problem is that the Zipline **latest** build has inconsistent requirements not caught/tested.

First, the **stable** build for Zipline and the current Alphalens package do indeed play well together. I can see that this is what is installed in Quantopian Research prod.

Concretely, following the zipline [travis CI yml file](https://github.com/quantopian/zipline/blob/master/.travis.yml), the **stable** build is:

```
conda create -n testenv -y python=3.5 numpy=1.11.3 pandas=0.18.1 scipy=0.17.1 libgfortran=3.0 pip
source activate testenv
python -m pip install -r requirements_stable.txt --no-cache-dir
python -m pip install -r requirements_blaze_stable.txt --no-cache-dir
pip install zipline==1.3.0 --no-cache-dir
pip install alphalens==0.3.2 --no-cache-dir
```

where the requirements files are those in `zipline/etc` (I renamed them here because they are [modified in place via](https://github.com/quantopian/zipline/blob/master/ci/travis/overwrite_requirements.sh) `sed` depending on stable/latest).

This works well

```
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipline
>>> import alphalens
>>> import blaze
>>> import pandas
```

However, when I try the **latest** zipline build,

```
conda create -n testenv_latest -y python=3.5 numpy=1.14.1 pandas=0.22.0 scipy=1.0.0 libgfortran=3.0 pip
source activate testenv_latest
python -m pip install -r requirements_latest.txt --no-cache-dir
python -m pip install -r requirements_blaze_latest.txt --no-cache-dir
pip install zipline==1.3.0 --no-cache-dir
pip install alphalens==0.3.2 --no-cache-dir
```

Where the `requirements_*latest.txt` files are those modified in place.

This does **not** work

```
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipline
>>> import alphalens
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/testenv_latest/lib/python3.5/site-packages/alphalens/__init__.py", line 1, in <module>
    from . import performance
  File "/anaconda3/envs/testenv_latest/lib/python3.5/site-packages/alphalens/performance.py", line 22, in <module>
    from statsmodels.regression.linear_model import OLS
  File "/anaconda3/envs/testenv_latest/lib/python3.5/site-packages/statsmodels/regression/__init__.py", line 1, in <module>
    from .linear_model import yule_walker
  File "/anaconda3/envs/testenv_latest/lib/python3.5/site-packages/statsmodels/regression/linear_model.py", line 43, in <module>
    from scipy.stats.stats import ss
ImportError: cannot import name 'ss'
>>>
```

Zipline latest runs on `scipy==1.0.0` with a requirement for `statsmodels==0.6.1`. However **I don't believe that these two requirements are consistent.** It looks like scipy changed its internals which statstmodels==0.6.1 doesn't understand. 

If I upgrade statsmodels, 
```
pip install statsmodels==0.9.0 --updgrade --no-cache-dir
```
Then they seem to play well

```
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:11) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipline
>>> import alphalens
>>> import scipy
>>> import statsmodels as sm
>>> sm.__version__
'0.9.0'
```

However it makes me nervous to bump statsmodels like this in conflict with the Zipline `requirements.txt`. Would it be possible for you to run the Travis CI tests with statsmodels==0.9.0?

(Note the requirements for alphalens show `statsmodels>=0.6.1`)

**Comment by Whamp** [comment]
Any update on this issue? Zipline 1.3 still internally conflicts on installation

**Comment by richafrank** [comment]
I updated the "latest" build in CI with statsmodels==0.9.0. Tests all pass! Closing this, but feel free to reopen if there's more to do. My hope for the next release is to improve our packaging/install situation generally.
